spring:
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: tnn2868491037@163.com #登陆账号
    password: sm123456 #登陆密码（或授权码）
    properties:
      from: tnn2868491037@163.com #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量